services:
  postgres:
    image: postgres:16-alpine
    container_name: simulador-frete-postgres
    environment:
      POSTGRES_DB: frete_teste
      POSTGRES_USER: frete_user
      POSTGRES_PASSWORD: frete_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U frete_user -d frete_teste"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: simulador-frete-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: