spring:
  application:
    name: frete-teste

  datasource:
    url: jdbc:postgresql://localhost:5432/frete_teste
    username: frete_user
    password: frete_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 86400000

server:
  port: 8080

brasilapi:
  cep-url: https://brasilapi.com.br/api/cep/v2/{cep}

logging:
  level:
    com.desafiogruporevise.frete_teste: DEBUG